import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ComingSoon from '../components/comingsoon'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>App Yubiai Market</title>
        <meta name="description" content="Generated by Yubiai Market" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <ComingSoon />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://yubiai.market/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Yubiai.market
        </a>
      </footer>
    </div>
  )
}

export default Home
